language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

directories:
  - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - cd tests/
  - php ../vendor/bin/phpunit --testdox

after_success:
- bash <(curl -s https://codecov.io/bash)
